import type { Metadata } from "next";
import { Sidebar } from "../_layout/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex">
        <Sidebar />
        <div className="w-[calc(100%-192px)] ml-auto mt-[56px]">{children}</div>
      </div>
    </>
  );
}
